# Generated by Django 6.0.2 on 2026-02-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='translator',
        ),
        migrations.DeleteModel(
            name='Translator',
        ),
    ]
